[project]
name = "minion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "langfuse>=4.14.5",
    "langgraph>=1.2.11",
    "openai>=3.5.0",
    "pymupdf>=1.28.2",
    "python-multipart>=0.0.32",
    "sentence-transformers>=6.0.0",
    "uvicorn[standard]>=0.52.4",
    "valkey>=6.1.1",
]
