import { useEffect, useRef } from 'react';
import { Renderer, Program, Mesh, Triangle, Color } from 'ogl';
import './SpecularButton.css';

const PAD=20;
const VERT=`#version 300 es
in vec2 position;void main(){gl_Position=vec4(position,0.,1.);}`;
const FRAG=`#version 300 es
precision highp float;
uniform vec2 uCenter,uHalfSize;uniform float uRadius,uAngle,uPx,uIntensity,uShineSize,uShineFade,uThickness,uBaseWidth;uniform vec3 uLineColor,uBaseColor;out vec4 fragColor;
float sdRoundedRect(vec2 p,vec2 b,float r){vec2 q=abs(p)-b+r;return length(max(q,0.))+min(max(q.x,q.y),0.)-r;}
float gaussianLine(float d,float sigma){float x=d/(sigma+1e-6);float k=mix(1.,1.6,smoothstep(0.,1.5,x));return exp(-k*x*x);}
void main(){vec2 p=gl_FragCoord.xy-uCenter;float d=sdRoundedRect(p,uHalfSize,uRadius);vec2 L=vec2(cos(uAngle),sin(uAngle));float base=(1.-smoothstep(0.,uBaseWidth,abs(d)))*.45;vec2 nEll=normalize(p/(uHalfSize*uHalfSize)+1e-6);float phi=acos(clamp(abs(dot(nEll,L)),0.,1.));float rim=1.-smoothstep(uShineSize-uShineFade,uShineSize+uShineFade+1e-4,phi);float line=gaussianLine(d,uThickness);float edgeClamp=1.-smoothstep(.5*uPx,3.*uPx,abs(d));float hi=line*rim*edgeClamp*uIntensity;vec3 col=uBaseColor*base+uLineColor*hi;fragColor=vec4(col,clamp(base+hi,0.,1.));}`;

export default function SpecularButton({children='Get Started',size='lg',radius=18,tint='#ffffff',tintOpacity=0,blur=0,textColor='#f5f5f5',lineColor='#ffffff',baseColor='#525252',intensity=1,shineSize=10,shineFade=40,thickness=1,speed=.35,followMouse=true,proximity=250,autoAnimate=false,onClick,className='',type='button'}){
  const btnRef=useRef(null),fxRef=useRef(null),propsRef=useRef({});
  propsRef.current={radius,lineColor,baseColor,intensity,shineSize,shineFade,thickness,speed,followMouse,proximity,autoAnimate};
  useEffect(()=>{const btn=btnRef.current,fx=fxRef.current;if(!btn||!fx)return;const dpr=devicePixelRatio||1;const renderer=new Renderer({alpha:true,premultipliedAlpha:true,antialias:true,dpr});const gl=renderer.gl;gl.clearColor(0,0,0,0);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE_MINUS_SRC_ALPHA);const geometry=new Triangle(gl);if(geometry.attributes.uv)delete geometry.attributes.uv;const program=new Program(gl,{vertex:VERT,fragment:FRAG,uniforms:{uCenter:{value:[0,0]},uHalfSize:{value:[1,1]},uRadius:{value:0},uAngle:{value:2.4},uPx:{value:dpr},uLineColor:{value:[1,1,1]},uBaseColor:{value:[.32,.32,.32]},uIntensity:{value:1},uShineSize:{value:.17},uShineFade:{value:.7},uThickness:{value:1},uBaseWidth:{value:dpr}}});const mesh=new Mesh(gl,{geometry,program});fx.appendChild(gl.canvas);const dimensions={w:1,h:1};const resize=()=>{const r=btn.getBoundingClientRect();dimensions.w=r.width;dimensions.h=r.height;renderer.setSize(r.width+PAD*2,r.height+PAD*2);program.uniforms.uCenter.value=[(PAD+r.width/2)*dpr,(PAD+r.height/2)*dpr];program.uniforms.uHalfSize.value=[r.width/2*dpr,r.height/2*dpr];};const ro=new ResizeObserver(resize);ro.observe(btn);resize();let pointerAngle=null,proximityT=0;const move=e=>{const r=btn.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=Math.max(r.left-e.clientX,0,e.clientX-r.right),dy=Math.max(r.top-e.clientY,0,e.clientY-r.bottom),dist=Math.hypot(dx,dy);pointerAngle=dist===0?Math.atan2(2/r.height,-2/r.width)+(e.clientX-cx)/r.width*.6+(cy-e.clientY)/r.height*.3:Math.atan2(cy-e.clientY,e.clientX-cx);const t=Math.max(0,1-dist/Math.max(propsRef.current.proximity,1));proximityT=t*t*(3-2*t);};window.addEventListener('pointermove',move);let angle=2.4,idleAngle=2.4,bright=0,last=performance.now(),raf=0;const lineC=new Color(),baseC=new Color();const update=now=>{raf=requestAnimationFrame(update);const dt=Math.min((now-last)/1000,.05);last=now;const p=propsRef.current;idleAngle+=p.speed*dt;const steer=p.followMouse&&pointerAngle!=null&&(!p.autoAnimate||proximityT>0),target=steer?pointerAngle:idleAngle,diff=((target-angle+Math.PI*3)%(Math.PI*2))-Math.PI;angle+=diff*(1-Math.exp(-dt*7));bright+=((p.autoAnimate?1:proximityT)-bright)*(1-Math.exp(-dt*8));lineC.set(p.lineColor);baseC.set(p.baseColor);Object.assign(program.uniforms.uAngle,{value:angle});program.uniforms.uRadius.value=Math.min(p.radius,Math.min(dimensions.w,dimensions.h)/2)*dpr;program.uniforms.uLineColor.value=[lineC.r,lineC.g,lineC.b];program.uniforms.uBaseColor.value=[baseC.r,baseC.g,baseC.b];program.uniforms.uIntensity.value=p.intensity*bright;program.uniforms.uShineSize.value=p.shineSize*Math.PI/180;program.uniforms.uShineFade.value=p.shineFade*Math.PI/180;program.uniforms.uThickness.value=p.thickness*dpr;renderer.render({scene:mesh});};raf=requestAnimationFrame(update);return()=>{cancelAnimationFrame(raf);ro.disconnect();window.removeEventListener('pointermove',move);gl.canvas.remove();gl.getExtension('WEBGL_lose_context')?.loseContext();};},[]);
  return <button ref={btnRef} type={type} onClick={onClick} className={`specular-button specular-button--${size} ${className}`} style={{'--sb-radius':`${radius}px`,'--sb-tint':tint,'--sb-tint-opacity':tintOpacity,'--sb-blur':`${blur}px`,'--sb-text-color':textColor}}><span ref={fxRef} className="specular-button__fx" aria-hidden="true"/><span className="specular-button__label">{children}</span></button>;
}
